name: cross-ui package

on:
  push:
    branches:
      - main
      
jobs:
  publish-gpr:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/checkout@v1
        with:
          node-version: 12
          registry-url: https://npm.pkg.github.com/
          scrope: '@kukalajet'
      - run: npm install --legacy-peer-deps
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
